[project]
name = "introducao-redes-complexas-usp-edicao-2026"
version = "0.1.0"
description = "Contém código escrito para acompanhar a disciplina de Introdução a Redes Complexas da USP - Edição 2026."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.6",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "pandas>=3.0.0",
    "ruff>=0.14.14",
    "scipy>=1.17.0",
]
